name = "SimpleAtomsStructures"
uuid = "5a5d92d7-a3f7-4436-85e1-8ad3c2f35372"
authors = ["Teemu Järvinen <teemu.j.jarvinen@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
ArgCheck = "2"
AtomsBase = "0.5"
StaticArrays = "1"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
